### PR TITLE
Adds a react/js implementation of the code challenge

### PR DESCRIPTION
**Pull request by ebenoist**

### CODE REVIEW

**Comment by kylecrum** [comment]
👍 Might be too well factored, but I can still see how people react when given the challenge of adding new headers.

**Comment by kylecrum** [comment]
@jeffmeyers we can make a list of ways to extend this if that helps. Been slightly different every time since people bring in different things.

**Comment by ebenoist** [comment]
@jeffmeyers great question. This is the baseline for the code challenge. We add on a few different steps to increase complexity.

Examples include:
1. Filter listings by clicking on a category
2. Paginate listings
3. Add new filters

**Comment by kylecrum** [comment]
@jeffmeyers in this sheet: https://docs.google.com/spreadsheets/d/18IEHQWTMQXtoPAfHITCDgpnd-iRCMQ5Rzxxr9R0IjZs/edit#gid=0

**Comment by kylecrum** [comment]
That is waaay more than anyone will get through because I like to slow down and refactor, but if there is a super coder person, that will fill up the time.

**Comment by sparkertime** [comment]
I like this quite a bit. Really appreciate create-react-app as the jumping off point for this, I think that will be a huge boon for juniors.

My only comment is that I think there's a different philosophy between your example and the Ruby one by @kylecrum . I think you've taken an approach of "Let's put our best foot forward" and I think Kyle took one of "Let's leave some rough edges and see how they refactor them."

If I'm correct, then I would like to have a unified approach to these submissions and we should probably talk IRL. If I'm wrong, then I may have just put @kylecrum on blast in a PR and I'm sorry about that.

**Comment by kylecrum** [comment]
Ya, the only change that I would make to be more in line with what I have is do not refactor into the API file and inline all of the http calls.

**Comment by kylecrum** [comment]
I did like the feedback I got into how it could be refactored. Sample size of 1 though

**Comment by ebenoist** [comment]
I disagree, the challenge literally says "put your best foot forward". I think we should set a precedent for what kind of code we expect from those candidates that cannot or are unwilling to submit a submission. This is the kind of challenge we would accept (I think).

If we want to make this a refactoring challenge, I can inline all the things and see how they react to change, but I don't want to plop someone into an environment I wouldn't necessarily want to start coding in.

I could see the challenge going either way and I am 100% comfortable with either approach here, but I agree we should get something consistent going.

**Pull request merged**
